blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸í•˜ê¸° / Ask a Question
    url: https://github.com/onesuit/workshop-translator/discussions
    about: ì§ˆë¬¸ì´ ìˆìœ¼ì‹œë©´ Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”!
